### PR TITLE
norm

### PR DESCRIPTION
**Pull request by lokkirill**

### CODE REVIEW

**Review by lokkirill — COMMENTED** [review]
norm

**Comment by kladaFOX** [comment]
> norm

NORM

**Comment by lokkirill** [comment]
> > norm
> 
> NORM

NORM or norm?

**Comment by kladaFOX** [comment]
> > > norm
> > 
> > 
> > NORM
> 
> NORM or norm?

NORM

**Comment by kladaFOX** [comment]
> > > > norm
> > > 
> > > 
> > > NORM
> > 
> > 
> > NORM or norm?
> 
> NORM

I would say FINE

**Pull request merged**
